### ISSUE TITLE
Tạo giao diện

### ISSUE THREAD

**Issue by ghost** [21130449-NguyenKhaiNam/harmony_chat#2]
Thực hiện chuyển toàn bộ giao diện từ figma sang file XML

**Comment by 21130449-NguyenKhaiNam** [comment]
Trong figma có sẵn chuyển đổi sáng android á ông mình không cần chuyển qua xml đâu khương

**Comment by 21130449-NguyenKhaiNam** [comment]
Hoàn tất kiểm tra và thiết kế giao diện trên figma -> Chuyển đổi sang android

**Comment by 21130449-NguyenKhaiNam** [comment]
#1:
Chuẩn bị xong các thành phần nhỏ nhất: chữ, kích thước, icon, màu sắc

**Comment by 21130449-NguyenKhaiNam** [comment]
#2:
Hoàn tất màn hình demo và phân chia các màn hình cho thành viên
