### ISSUE TITLE
Tạo kết nối

### ISSUE THREAD

**Issue by ghost** [21130449-NguyenKhaiNam/harmony_chat#3]
Sau khi tạo workspace thì tạo connection với railway
Sử dụng connection pool, jdbc (hoặc kết hợp jdbi)

**Comment by 21130449-NguyenKhaiNam** [comment]
# Cấu hình thông tin kết nối
spring.application.name=harmony_chat
#databasse
spring.datasource.url=jdbc:mysql://root:HvIofozeOAFqkOjRnfkMqmRIpPkAmTVi@roundhouse.proxy.rlwy.net:29567/railway
spring.datasource.username=root
spring.datasource.password=HvIofozeOAFqkOjRnfkMqmRIpPkAmTVi


#jpa configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true
